name: Upload docs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up OCaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.10.0

      - name: Build
        run: |
          eval $(opam env)
          opam install odoc
          opam install ./plist-xml.opam ./plist-xml-lwt.opam
          dune build @doc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/default/_doc/_html
