name: install-test

on:
  push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.11.1

      - name: Build
        run: |
          eval $(opam env)
          opam install . --with-test
