name: install-test

on:
  push

jobs:
  build:
    strategy:
      matrix:
        ocaml-version:
          - 4.08.1
          - 4.11.1

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Build
        run: |
          eval $(opam env)
          opam install . --with-test
