name: install-test

on:
  push

jobs:
  build:
    strategy:
      matrix:
        ocaml-compiler:
          - 5.0.x

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Build
        run: opam install . -t
